name: Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test CooksCornerAPPTests/CooksCornerAPPTests.csproj

    - name: Push changes to dev branch
      if: steps.test.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        branch: dev
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}